version: "3"
services:
  db:
    image: postgres:11
    env_file:
      - ./db/dev.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata/
    ports:
      - 5432:5432
    volumes:
      - ./db/.data:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    build:
      context: ./api/
      dockerfile: dev.Dockerfile
    env_file:
      - ./api/dev.env
    ports:
      - 3000:3000
    volumes:
      - ./api/:/usr/src/app/
  