version: "3"
services:
  db:
    image: postgres:11
    env_file:
      - .env.dev
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    depends_on:
      - api
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - PORT=80
    stdin_open: true
    ports:
      - 80:80
    volumes:
      - ./client:/app
      - /app/node_modules
  