version: "3"
services:
 db:
  image: postgres:11
  environment:
   - POSTGRES_USER=$DB_ADMIN_USR
   - POSTGRES_PASSWORD=$DB_ADMIN_PWD
  ports:
   - 5432:$DB_PORT
  volumes:
   - ./data:/var/lib/postgresql/data
  restart: always
 api:
  image: nicodes/ctcalc-api
  depends_on:
   - db
  environment:
   - NODE_ENV=$API_NODE_ENV
   - PORT=$API_PORT
   - PGHOST=db
   - PGPORT=$DB_PORT
   - PGDATABASE=$DB_NAME
   - PGUSER=$DB_API_USR
   - PGPASSWORD=$DB_API_PWD
  ports:
   - $API_PORT:$API_PORT
 ui:
  image: nginx
  ports:
   - 80:80
  volumes:
   - ./build:/usr/share/nginx/html
