version: "3"
services:
  db:
    image: postgres:11
    env_file:
      - .env.prod.db
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata/
    ports:
      - 5432:5432
    volumes:
      - /root/app/pgdata/:/var/lib/postgresql/data/pgdata/
  api:
    image: nicodes/ctcalc-api
    depends_on:
      - db
    env_file:
      - .env.prod.api
      # - ./api/.env.prod # local testing
    ports:
      - 8080:8080
  server:
    image: nginx
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf # TODO get reverse proxy working
      - /root/app/build/:/usr/share/nginx/html/
      # - ./client/build/:/usr/share/nginx/html/ # local testing
    