version: "3"
services:
 db:
  image: postgres:11
  environment:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
   - API_USER
   - API_PASSWORD
  ports:
   - $DB_PORT:$DB_PORT
  volumes:
   - ./db/data:/var/lib/postgresql/data
   - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
   - ./db/dump.sql.gz:/app/dump.sql.gz
  restart: always
  command: -p $DB_PORT
 api:
  depends_on:
   - db
  build:
   context: ./api
   dockerfile: Dockerfile.dev
  environment:
   - NODE_ENV
   - PORT=$API_PORT
   - PGHOST
   - PGPORT
   - PGDATABASE
   - PGUSER
   - PGPASSWORD
  ports:
   - $API_PORT:$API_PORT
  volumes:
   - ./api:/app
   - /app/node_modules
 ui:
  depends_on:
   - api
  build:
   context: ./ui
   dockerfile: Dockerfile.dev
  environment:
   - NODE_ENV
   - PORT=$UI_PORT
   - REACT_APP_API_HOST
  ports:
   - $UI_PORT:$UI_PORT
  volumes:
   - ./ui:/app
   - /app/node_modules
  stdin_open: true
