version: "3"
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile.prod
    image: nicodes/ctcalc-api
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile.prod
    volumes:
      - ./client/build/:/app/build/
    env_file:
      - ./prod/.env.client
