version: "3"
services:
 db:
  image: postgres:11
  environment:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
   - API_USER
   - API_PASSWORD
  ports:
   - $DB_PORT:$DB_PORT
  volumes:
   - ./db/data:/var/lib/postgresql/data
   - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
   - ./db/dump.sql.gz:/app/dump.sql.gz
  restart: always
  command: -p $DB_PORT
 api:
  image: nicodes/ctcalc-api
  depends_on:
   - db
  environment:
   - NODE_ENV
   - PORT=$API_PORT
   - PGHOST
   - PGPORT
   - PGDATABASE
   - PGUSER
   - PGPASSWORD
  ports:
   - $API_PORT:$API_PORT
 ui:
  image: nginx
  depends_on:
   - api
  environment:
   - NODE_ENV
   - REACT_APP_API_HOST
  ports:
   - 80:80
  volumes:
   - ./build:/usr/share/nginx/html
   # - ./nginx.conf:/etc/nginx/nginx.conf # TODO get reverse proxy working
