version: "3"
services:
 db:
  image: postgres:11
  environment:
   - POSTGRES_USER=$DB_ADMIN_USR
   - POSTGRES_PASSWORD=$DB_ADMIN_PWD
  ports:
   - 5432:$DB_PORT
  volumes:
   - ./db/data:/var/lib/postgresql/data
  restart: always # TODO check this
 api:
  depends_on:
   - db
  build: ./api
  environment:
   - NODE_ENV=$API_NODE_ENV
   - PORT=$API_PORT
   - PGHOST=db
   - PGPORT=$DB_PORT
   - PGDATABASE=$DB_NAME
   - PGUSER=$DB_API_USR
   - PGPASSWORD=$DB_API_PWD
  ports:
   - $API_PORT:$API_PORT
  volumes:
   - ./api:/app
   - /app/node_modules
 ui:
  depends_on:
   - api
  build: ./ui
  environment:
   - NODE_ENV=$UI_NODE_ENV
   - PORT=$UI_PORT
   - REACT_APP_API_URL
  ports:
   - $UI_PORT:$UI_PORT
  volumes:
   - ./ui:/app
   - /app/node_modules
  stdin_open: true
