version: "3"
services:
  db:
    image: postgres:11
    env_file:
      - .env.prod
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  api:
    image: nicodes/ctcalc-api
    depends_on:
      - db
    env_file:
      - .env.prod
    ports:
      - 8080:8080
  server:
    image: nginx
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ./build:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/nginx.conf # TODO get reverse proxy working
