name: Publish Docker image
on: push:
  branches:
  - master
jobs:
  slack-notify:
    name: Slack Notify
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: Dockerfile.prod
          # platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: nicodes/ctcalc-api