name: Publish Docker image
on:
  push:
    branches: master
jobs:
  slack-notify:
    name: Slack Notify
    runs-on: ubuntu-latest
    steps:
    - Slack Notify:
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  api-build:
    runs-on: ubuntu-latest
    steps:
      - Checkout:
        uses: actions/checkout@v2
      - Set up QEMU:
        uses: docker/setup-qemu-action@v1
      - Set up Docker Buildx:
        uses: docker/setup-buildx-action@v1
      - Login to DockerHub:
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - Build and Push:
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile.prod
          push: true
          tags: nicodes/ctcalc-api
  ui-build:
    runs-on: ubuntu-latest
    steps:
    - Checkout:
      uses: actions/checkout@v2
    - Setup Node.js:
      uses: actions/setup-node@v1
      with:
        node-version: '14.14'
    - Install Dependenceis:
      working-directory: ./ui
      run: npm i --production
    - Build UI:
      working-directory: ./ui
      run: npm run build
    - Copy Build to Remote:
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        source: './ui/build'
        target: '~/app/build'
        rm: true