name: Pull request checks
on: pull_request
jobs:
  cypress-tests:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: cypress-io/github-action@v5
        with:
          # install: false
          install-command: pnpm install --frozen-lockfile
          working-directory: web
          build: pnpm run build:local
          start: pnpm run preview:local
