name: Run E2E tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Cache node modules
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies if needed
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Serve
        run: pnpm run preview:node

      - name: Serve
        run: pnpm run test:preview
