name: Pull request checks
on: pull_request
jobs:
  cypress_tests:
    name: Cypress tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: yarn build
          start: yarn preview
