name: Pull request checks
on: pull_request
jobs:
  cypress-tests:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            cwd: web
      - uses: cypress-io/github-action@v5
        with:
          build: yarn build:local
          start: yarn preview:local
          working-directory: web
