name: Pull request checks
on: pull_request
jobs:
  cypress-tests:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: cypress-io/github-action@v5
        with:
          working-directory: web
          install-command: pnpm i --frozen-lockfile
          build: pnpm run build:node
          start: pnpm run preview:node
          command: pnpm run test:preview
