name: Pull request checks
on: pull_request
jobs:
  cypress_tests:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          NODE_ADAPTER: true
        with:
          build: yarn build
          start: yarn preview
          working-directory: ./web
